---
# Role to prepare base OS image from which all other are derived
#
# If VIRTHOST is in RHEL7 or equivalent extra steps are required
# to run RHEL8 guest (download libguestfs appliance, extract and
# set  environment LIBGUESTFS_PATH to /path/to/appliance/)
#
# URL:
# http://download.libguestfs.org/binaries/appliance/appliance-1.40.1.tar.xz
#
# Since I am on a newer OS no need for all that
#

- name: Base OS image
  become: yes
  environment:
    LIBGUESTFS_BACKEND: direct
    LIBVIRT_DEFAULT_URI: 'qemu+ssh://stack@localhost/system'
  block:

    - name: Check if image already exists
      stat:
        path: "{{ target_image }}"
      register: image_p

    - block:

      - name: Create image dir if not there
        file:
          path: "{{ image_dst_dir }}"
          state: directory
          owner: root
          group: root
          mode: '755'
          serole: object_r
          setype: virt_image_t
          seuser: system_u

      - name: Fetch OS image
        get_url:
          url: "{{ image_url }}"
          dest: "{{ temp_image }}"
        when:
          - image_source == 'url'

      - name: "Create empty {{ target_image }} of 50G"
        command: "/usr/bin/qemu-img create -f qcow2 {{ target_image }} 50G"
        become_user: root

      - name: "Clone {{ temp_image }} into {{ target_image }}"
        command: "/usr/bin/virt-resize --expand /dev/sda1 {{ temp_image }} {{ target_image }}"

      - name: Set root password and remove cloud-init
        command: "/usr/bin/virt-customize -a {{ target_image }} --root-password password:redhat --uninstall cloud-init"
        no_log: true

      - name: Send ssh keys in conf for root access
        command: "/usr/bin/virt-customize -a {{ target_image }} --ssh-inject root:string:'{{ ssh_pubkey }}'"
        # TODO: Change to file
        #command: "/usr/bin/virt-customize -a {{ target_image }} --ssh-inject root:file:/home/{{ username }}/.ssh/id_rsa.pub'"
        no_log: true

      - name: Set eth1 config
        command: "/usr/bin/virt-customize -a {{ target_image }} --run-command 'cp /etc/sysconfig/network-scripts/ifcfg-eth{0,1} && sed -i s/DEVICE=.*/DEVICE=eth1/g /etc/sysconfig/network-scripts/ifcfg-eth1'"

      - name: "Cleanup {{ temp_image }}"
        file:
          path: "{{ temp_image }}"
          state: absent

      when:
        - image_p.stat.islnk is not defined
      tags:
        - baseimage

...
