---
- name: Bootstrap RHOSP
  hosts: localhost
  become: yes
  gather_facts: no
  roles:
    - baseimage
          #- sysctl
          #- repos
          #- libvirt
          #- packages
          #- modprobe
          #- proxy
...
