---
- name: Bootstrap RHOSP
  hosts: localhost
  become: yes
  gather_facts: no
  roles:
    - repos
    - packages
    - sysctl
    - modprobe
    - libvirt
    - proxy
    - baseimage
    - vms
...
