# Create a new VM
- name: "Create vm {{ name }}"
  become: yes
  block:

    - name: "Create {{ name }} volume overlay"
      command: "/usr/bin/qemu-img create -f qcow2 -b {{ target_image }} {{ image_dst_dir }}/{{ name }}.qcow2 "

    - name: "Create {{ name }} VM"
      command: "/usr/bin/virt-install --ram  {{ ram }} --vcpus {{ vcpus }} --os-variant rhel7 --disk path={{ image_dst_dir }}/{{ name }}.qcow2,device=disk,bus=virtio,format=qcow2 --import --noautoconsole --vnc --network network:provisioning --network network:default --name {{ name }}"

...
