---
- name: Packages - Common required packages
  dnf:
    pkg: "{{ item }}"
    state: present
  with_items:
    - curl
    - net-tools
    - tmux
    - wget
    - xorg-x11-apps
    - xauth
    - xorg-x11-fonts-Type1
    - xz
  tags:
    - packages


