---
- name: Proxy - Install squid related packages
  dnf: 
    name: "{{item}}"
    state: present
  with_items:
    - squid
  notify: "Proxy - Restart squid"
  tags:
    - proxy_install

- name: enable squid
  service: 
    name: squid
    enabled: yes
  tags:
    - proxy_enable

- name: firewall allow permanent
  firewalld:
    service: squid
    permanent: true
    immediate: true
    state: enabled
  tags:
    - proxy_firewall

...
