---
- name: Proxy - Install squid related packages
  dnf:
    name: "{{item}}"
    state: present
  with_items:
    - squid
  notify: "Proxy - Restart squid"
  tags:
    - proxy
    - prereqs

- name: enable squid
  service:
    name: squid
    enabled: yes
  tags:
    - proxy
    - prereqs

- name: firewall allow permanent
  firewalld:
    service: squid
    permanent: true
    immediate: true
    state: enabled
  tags:
    - proxy
    - prereqs

...
