---
# Prepare Libvirt
- name: Install
  dnf:
    pkg: "{{item}}"
    state: present
  with_items:
    - libvirt
    - libguestfs-tools
    - libguestfs-xfs
    - qemu-kvm
    - virt-manager
    - virt-install
    - virt-viewer
    - python3-lxml
  tags:
    - libvirt
    - prereqs

- name: Add relevant users to libvirt group
  user: name={{ username }} groups=libvirt append=yes
  notify: restart libvirtd
  tags:
    - libvirt
    - prereqs

- name: Enable and start service
  service: name=libvirtd.service enabled=yes state=started
  tags:
    - libvirt
    - prereqs

- name: Setup networks
  include: net.yml net={{ item }}
  with_items:
    - "{{ libvirt_network_list }}"
  tags:
   - libvirt
   - prereqs
...
