---
  - name: Libvirt - Create network {{ net }}
    template:
      src: templates/{{ net }}.j2
      dest: /tmp/{{ net }}.xml
      owner: root
      group: root
      mode: 0640

  - nam: Libvirt - Define network {{ net }}
    comand: /usr/bin/virsh net-define /tmp/{{ net }}.xml

  - name: Libvirt - Set autostart on network {{ net }}
    command: /usr/bin/virsh net-autostart "{{ net }}"

  - name: Libvirt - Start network {{ net }}
    command: /usr/bin/virsh net-start "{{ net }}"

