# Templates and the required variables below must exist for each network listed
libvirt_network_list:
  - default
  - provisioning
  - external

# Director network settings
# required by templates/provisioning.xml.j2
provisioning_net_ip: 192.168.24.1
provisioning_net_netmask: 255.255.255.0
#default_bridge`: virbr1

# default network settings
# required by templates/default.xnl.j2
default_net_ip: 192.168.122.1
default_net_netmask: 255.255.255.0
#default_mac: '52:54:00:c7:15:90'
default_net_dev: enp2s0
default_bridge`: virbr0

# external network settings
# required by templates/external.xml.j2
#external_net_ip: 192.168.3.251
#external_net_netmask: 255.255.255.0
#external_net_dev: enp2s0
external_bridge: br0
