# Templates and the required variables below must exist for each network listed
libvirt_network_list:
  - default
  - provisioning

# Director network settings
# required by templates/provisioning.j2
provisioning_net_ip: 192.168.0.254
provisioning_net_netmask: 255.255.255.0

# external network settings
# required by templates/default.j2
default_net_ip: 192.168.0.254
default_net_netmask: 255.255.255.0
#default_mac: '52:54:00:c7:15:90'
default_net_dev: enp2s0
default_bridge: br0

# Url for libvirt RHEL7 image
# curl -o /var/lib/libvirt/images/rhel7-guest-official.qcow2 http://10.12.50.1/pub/rhel-guest-image-7.3-35.x86_64.qcow2
rhel7_image_url: http://10.12.50.1/pub/rhel-guest-image-7.3-35.x86_64.qcow2
rhel7_image_dst: /var/lib/libvirt/images/rhel7-guest-official.qcow2
