---

- name: "Create undercloud VM"
  include: undercloud.yml
  tags:
    - undercloud

# Create overcloud VMs
- name: "Create overcloud VMs"
  include: vm.yml name={{ item.name }} ram={{ item.ram }} vcpus={{ item.vcpus }} ceph={{ item.ceph }} externalnet={{ item.externalnet }} empty_root={{ item.empty_root }}
  loop: "{{ overcloud|list }}"
  loop_control:
    label: "{{ item.name }}"
  tags:
    - overcloud
...
