---
- name: Create group for user {{ username }}
  group:
    name: {{ username }}
    gid: 9999
    state: present
  tags:
    - users
    - prereqs

- name: Create user {{ username }}
  user:
    name: {{ username }}
    comment: "RHOSP deployment user"
    createhome: yes
    group: {{ username }}
    groups: wheel
    append: yes
    shell: /bin/bash
    uid: 9999
    update_password: on_create
    state: present
    password: "$6$A6Fr7CCy5sJg508S$jr93cfx5vAhkjSWcWckwvoD5IdNIEx0Ja1ab5kCaSl/4SmADRWHKa/XQJ2Ku0HbsyhXSiQM0.8PgbKKnCbIj9/"
  tags:
    - users

- name: Create sudo entry for  {{ username }}
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '{{ username }} ALL='
    line: '{{ username }} ALL=(ALL) NOPASSWD: ALL'
    validate: /usr/sbin/visudo -cf %s
  tags:
    - users

- name: Create polkit entry to allow libvirt for {{ username }}
  template:
    src: 50-libvirt-user-rhosp.kla
    dst: /etc/polkit-1/localauthority/50-local.d/50-libvirt-user-rhosp.pkla
    mode: 0640
    seuser: system_u
    serole: object_r
    setype: etc_t
  tags:
    - users

