---
- name: Adding module config for kvm_intel
  lineinfile:
    path: /etc/modprobe.d/kvm.conf
    regexp: '^options kvm_intel {{ item }}'
    line: 'options kvm_intel {{ item }}=1'
  with_items:
    - nested
    - enable_shadow_vmcs
    - enable_apicv
    - ept
  tags:
    - modprobe
    - prereqs

- name: Enable module kvm_intel
  modprobe:
    name: "{{ item }}"
  with_items:
    - kvm
    - kvm_intel
  tags:
    - modprobe
    - prereqs
